name: Auto Update World Cup Ranking

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run script
        run: python script.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "auto update" || echo "no changes"
          git push
