name: Auto Update World Cup Ranking

on:
  push:
  workflow_dispatch:
  schedule: []

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - run: python script.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "auto update" || echo "no changes"
          git push
